--- # Ansible Playbook to configure a set of Raspberry PIs in a consistent and repeatable way
# Software installation and configuration
- hosts: calendar_service
  remote_user: "{{ user }}"
  become: yes
  vars:
    src_dir: "{{ playbook_dir }}"
    mode: u=rwx
    keycloak_server_host: "{{ lookup('env', 'KEYCLOAK_SERVER_HOST') }}"
    keycloak_server_port: "{{ lookup('env', 'KEYCLOAK_SERVER_PORT') }}"
    keycloak_service: "{{ lookup('env', 'KEYCLOAK_SERVICE') }}"
    keycloak_client_secret: "{{ lookup('env', 'KEYCLOAK_CLIENT_SECRET') }}"
  vars_files:
    - "{{ src_dir }}/conf/config.yaml"
  tasks:
    #################################################################
    ##### Windfire Calendar server component deployment Section #####
    #################################################################
    - import_tasks: tasks/deploy-app.yaml
  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes
